version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-django_prod_db}
      - POSTGRES_USER=${POSTGRES_USER:-django_prod_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-django_prod_user} -d ${POSTGRES_DB:-django_prod_db}"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  web:
    build: .
    restart: always
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 config.wsgi:application
    volumes:
      - static_volume_prod:/app/staticfiles
      - media_volume_prod:/app/media
    expose:
      - "8000"
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=config.settings_docker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume_prod:/app/staticfiles
      - media_volume_prod:/app/media
    depends_on:
      - web
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data_prod:
  redis_data:
  static_volume_prod:
  media_volume_prod: